# Starter pipeline
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
    failOnStderr: true